environment:
  DO_SPACES_ENDPOINT: ${DO_SPACES_ENDPOINT}
  DO_SPACES_ACCESS_KEY: ${DO_SPACES_ACCESS_KEY}
  DO_SPACES_SECRET_KEY: ${DO_SPACES_SECRET_KEY}
  DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}
  DO_AGENTAI_ENDPOINT: ${DO_AGENTAI_ENDPOINT}
  DO_AGENTAI_API_KEY: ${DO_AGENTAI_API_KEY}
  ENDPOINT_AUTH_URL: ${ENDPOINT_AUTH_URL}
  ENDPOINT_AUTH_USER: ${ENDPOINT_AUTH_USER}
  ENDPOINT_AUTH_PASSWORD: ${ENDPOINT_AUTH_PASSWORD}
  ENDPOINT_AUTH_KEY: ${ENDPOINT_AUTH_KEY}
  ENDPOINT_URL_TRANSCRIPTION: ${ENDPOINT_URL_TRANSCRIPTION}
  PROCESSING_BATCH_SIZE: ${PROCESSING_BATCH_SIZE}
  DELETE_PROCESSED_FILES: ${DELETE_PROCESSED_FILES}
  SKILL_CONFIG_JSON: ${SKILL_CONFIG_JSON}
packages:
  - name: conversation-processing
    actions:
      - name: anonymize-conversation
        runtime: 'python:3.11'
        binary: false
        web: false  
        limits:
          memory: 1024
          timeout: 900000